spring:
  application:
    name: auth-biv-service

  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
  jpa:
    hibernate:
        show_sql: true
        ddl_auto: none

  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/user_db

token:
  availableAttempts: 2
  tokenLifeTime: 2
  retryInterval: 1